version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.2.0
    container_name: "elasticsearch"
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.security.enabled: "false"
      xpack.monitoring.templates.enabled: "true"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - app_network

  logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    ports:
      - "9600:9600"
      - "8080:8080"
      - "4718:4718/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    networks:
      - app_network
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.2.0
    container_name: "kibana"
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - app_network

volumes:
  esdata:
    name: elasticsearch_vol
    driver: local

networks:
  app_network:
    driver: bridge
    name: elk_network
